yoo = {
"af": "Afrikaans",
"sq": "Albanian - shqip",
"am": "Amharic - አማርኛ",
"ar": "Arabic - العربية",
"hy": "Armenian - հայերեն",
"az": "Azerbaijani - azərbaycan dili",
"bn": "Bengali - বাংলা",
"bs": "Bosnian - bosanski",
"bg": "Bulgarian - български",
"ca": "Catalan - català",
"zh": "Chinese - 中文",
"zh-Hans": "Chinese (Simplified) - 中文（简体）",
"zh-Hant": "Chinese (Traditional) - 中文（繁體）",
"hr": "Croatian - hrvatski",
"cs": "Czech - čeština",
"da": "Danish - dansk",
"nl": "Dutch - Nederlands",
"en": "English",
"et": "Estonian - eesti",
"fj": "Fijian - føroyskt",
"fil": "Filipino",
"fi": "Finnish - suomi",
"fr": "French - français",
"de": "German - Deutsch",
"el": "Greek - Ελληνικά",
"gu": "Gujarati - ગુજરાતી",
"ht": "Haitian Creole",
"he": "Hebrew - עברית",
"hi": "Hindi - हिन्दी",
"mww": "Hmong Daw",
"hu": "Hungarian - magyar",
"is": "Icelandic - íslenska",
"id": "Indonesian - Indonesia",
"iu": "Inuktitut",
"ga": "Irish - Gaeilge",
"it": "Italian - italiano",
"ja": "Japanese - 日本語",
"kn": "Kannada - ಕನ್ನಡ",
"kk": "Kazakh - қазақ тілі",
"km": "Khmer - ខ្មែរ",
"ko": "Korean - 한국어",
"ku": "Kurdish - Kurdî",
"lo": "Lao - ລາວ",
"la": "Latin",
"lv": "Latvian - latviešu",
"lt": "Lithuanian - lietuvių",
"mg": "Malagasy - मराठी",
"ms": "Malay - Bahasa Melayu",
"ml": "Malayalam - മലയാളം",
"mt": "Maltese - Malti",
"mn": "Mongolian - монгол",
"ne": "Nepali - नेपाली",
"no": "Norwegian - norsk",
"or": "Oriya - ଓଡ଼ିଆ",
"ps": "Pashto - پښتو",
"fa": "Persian - فارسی",
"pl": "Polish - polski",
"pt": "Portuguese - português",
"pt-pt": "Portuguese (Portugal)",
"pa": "Punjabi - ਪੰਜਾਬੀ",
"ro": "Romanian - română",
"ru": "Russian - русский",
"sr-Cyrl": "Serbian - српски",
"sr-Latn": "Serbian - српски",
"sd": "Sindhi",
"si": "Sinhala - සිංහල",
"sk": "Slovak - slovenčina",
"sl": "Slovenian - slovenščina",
"es": "Spanish - español",
"sw": "Swahili - Kiswahili",
"sv": "Swedish - svenska",
"tg": "Tajik - тоҷикӣ",
"ta": "Tamil - தமிழ்",
"tt": "Tatar",
"te": "Telugu - తెలుగు",
"th": "Thai - ไทย",
"ti": "Tigrinya - ትግርኛ",
"to": "Tongan - lea fakatonga",
"tr": "Turkish - Türkçe",
"uk": "Ukrainian - українська",
"ur": "Urdu - اردو",
"vi": "Vietnamese - Tiếng Việt",
"cy": "Welsh - Cymraeg",
}


def language_name(lang):
    return yoo[lang]

if __name__ == "__main__":
    language_name(lang)
